# Generated by Django 4.2.6 on 2023-10-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tema', models.CharField(choices=[('A', 'Acao'), ('C', 'Comedia'), ('D', 'Drama'), ('F', 'Ficcao Cientifica')], max_length=50)),
                ('indicacao', models.CharField(choices=[('L', 'Livre'), ('10', '10+'), ('12', '12+'), ('14', '14+'), ('16', '16+'), ('18', '18+')], max_length=10)),
                ('estreia', models.DateField()),
                ('atores_principais', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
            ],
        ),
    ]
