# Generated by Django 4.2.6 on 2023-10-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0002_alter_filmes_deslikes_alter_filmes_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='likes',
        ),
        migrations.AddField(
            model_name='filmes',
            name='imagem',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='LikeDeslikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('deslikes', models.IntegerField(default=0)),
                ('id_filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmesflix.filmes')),
            ],
        ),
    ]
