# Generated by Django 4.2.6 on 2023-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0004_alter_filmes_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='imagem',
        ),
        migrations.AddField(
            model_name='filmes',
            name='deslikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filmes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filmes',
            name='url_imagem',
            field=models.TextField(default='https://bookemporiumbd.com/assets/images/default/default-product-img.jpg'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='indicacao',
            field=models.CharField(choices=[('Livre', 'Livre'), ('10+', '10+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='tema',
            field=models.CharField(choices=[('Acao', 'Acao'), ('Aventura', 'Aventura'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Ficcao Cientifica', 'Ficcao Cientifica'), ('Guerra', 'Guerra'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Animacao', 'Animacao'), ('Musical', 'Musical'), ('Crime', 'Crime'), ('Historia Real', 'Historia Real')], max_length=50),
        ),
        migrations.DeleteModel(
            name='LikeDeslikes',
        ),
    ]
