# Generated by Django 4.2.6 on 2023-10-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0005_remove_filmes_imagem_filmes_deslikes_filmes_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='url_imagem',
            field=models.TextField(),
        ),
    ]
