# Generated by Django 4.2.6 on 2023-10-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0006_alter_filmes_url_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='likes',
        ),
        migrations.AddField(
            model_name='filmes',
            name='avaliacao',
            field=models.FloatField(default=0.0),
        ),
    ]
