# Generated by Django 4.2.6 on 2023-10-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0007_remove_filmes_deslikes_remove_filmes_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='avaliacao',
            field=models.IntegerField(default=0),
        ),
    ]
