# Generated by Django 4.2.6 on 2023-10-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0008_alter_filmes_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='avaliacao',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
