# Generated by Django 4.2.6 on 2023-10-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0009_alter_filmes_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='total_votos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
