# Generated by Django 4.2.6 on 2023-10-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0010_filmes_total_votos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name_plural': 'filmes'},
        ),
    ]
