# Generated by Django 4.2.6 on 2023-10-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0011_alter_filmes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='total_votos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
