# Generated by Django 4.2.6 on 2023-11-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0013_alter_filmes_indicacao_alter_filmes_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='total_votos',
        ),
    ]
