# Generated by Django 4.2.6 on 2023-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmesflix', '0014_remove_filmes_avaliacao_remove_filmes_total_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='indicacao',
            field=models.CharField(choices=[('Livre', 'Livre'), ('10+', '10+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='tema',
            field=models.CharField(choices=[('Acao', 'Acao'), ('Aventura', 'Aventura'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Ficcao Cientifica', 'Ficcao Cientifica'), ('Guerra', 'Guerra'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Animacao', 'Animacao'), ('Musical', 'Musical'), ('Crime', 'Crime'), ('Historia Real', 'Historia Real')], max_length=50),
        ),
    ]
